# Page settings
baseurl = "https://www.studenthack.com"
title = "StudentHack V"
publishdir = "public"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = "css/custom1.css"

  # Meta
  author = "StudentHack V"
  description = "StudentHack V 2017 - #learn #build #share 10-12 March 2017"
  email = "hristeaanais@gmail.com"
  # Navigation
  [params.navigation]
    brand = "StudentHack V"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    tracks = "Tracks"
    sponsors = "Sponsors"
    chart = "Attendance"
    location = "Location"
    contact = "Get In Touch"
    challenges = "Challenges"

    # postpended links
    #[[menu.postpend]]
    #  url = "/challenges"
    #  name = "Challenges"
    #  weight = 10
 
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10


  # Hero section
  [params.hero]
    title = "10-12 March 2017 <br> Manchester, England"
    subtitle = "The epic student hackathon in Manchester <br> & we're making it more accessible than ever."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Yes, 100%."
      icon = "icon-wallet"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "All enrolled students over 18 and those who graduated in the last one year."
      icon = "icon-graduation"

    [[params.faq.item]]
      title = "What if I study outside the UK?"
      description = "You are still welcome to join us! However, we cannot sponsor visas."
      icon = "icon-plane"

    [[params.faq.item]]
      title = "I haven't coded much. Should I come?"
      description = "Hackathons are for beginners. Networking with and seeing awesome hackers in action will expose you to a tremendous amount of knowledge. There is an amazing suit of industry experts and mentors that are happy to assist you!"
      icon = "icon-briefcase"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone and chargers. Other things to consider: spare clothes, adapters, hardware and a sleeping bag, oh and don't forget your enthusiasm! We are going to provide you with all the food, swag, sleeping rooms and the drinks that you will need."
      icon = "icon-basket-loaded"

    [[params.faq.item]]
      title = "I don't have a team. Help?"
      description = "We encourage everybody to form a team with new people, regardless of whether you come with your buddies or not! We will organise a team-building session, where you will meet other participants just like you. Due to logistic restrictions, we ask for the teams to be of 4 people maximum."
      icon = "icon-people"

    [[params.faq.item]]
      title = "What can I expect from StudentHack?"
      description = "An entire weekend of great company, good food and plenty of swag! We'll also have hardware and tons of mentors."
      icon = "icon-magic-wand"

    [[params.faq.item]]
      title = "Who owns my IP/code/idea?"
      description = "You own all the rights to your intellectual property. We won't claim any right over anything made during this event."
      icon = "icon-bulb"

    [[params.faq.item]]
      title = "Do you have a code of conduct?"
      description = "Yes! We strictly adhere to the <a href='https://static.mlh.io/docs/mlh-code-of-conduct.pdf'>Major League Hacking Code of Conduct</a>."
      icon = "icon-book-open"

  # Schedule section
  [params.schedule]
    enable = true
    title = "Schedule"

    [[params.schedule.friday]]
      time = "18:00"
      name = "Registration opens"

    [[params.schedule.friday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.friday]]
      time = "20:30"
      name = "Opening ceremony"

    [[params.schedule.friday]]
      time = "22:00"
      name = "Hacking starts<br>Team forming session"


    [[params.schedule.saturday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.saturday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.saturday]]
      time = "21:00"
      name = "MLH event"


    [[params.schedule.sunday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.sunday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.sunday]]
      time = "10:00"
      name = "Hacking ends"

    [[params.schedule.sunday]]
      time = "11:00"
      name = "Judging starts"

    [[params.schedule.sunday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.sunday]]
      time = "14:00"
      name = "Final presentations"

    [[params.schedule.sunday]]
      time = "16:00"
      name = "Closing ceremony"

    [[params.schedule.sunday]]
      time = "17:00"
      name = "End of the event"

      # Tracks section
      [params.tracks]
        enable = true
        title = "Tracks"

        [[params.tracks.item]]
          title = "Fintech"
          description = "With the aid of technology, challenge the current status quo set by the traditional financial sector. Manage payment, provide insurance and trading advice, and automate tax returns. The possibilities are endless and only more money awaits! Barclays realised those potentials and are offering dedicated expertise advise and full support to this track. Join this track."
          icon = "icon-credit-card"

        [[params.tracks.item]]
          title = "Gaming"
          description = "Want to spend a weekend creating a game? The “Gaming” track brings together hackers who are passionate about games to develop, design, and create games. WebAppsUK is aiming to foster your creative side and they’re fully backing this track with dedicated mentors to help you take on our Gaming challenge and create the next Half-life game and become the StudentHack’s Gaming Challenge Winner."
          icon = "icon-game-controller"

        [[params.tracks.item]]
          title = "Security"
          description = "Whether you have something to hide, or not, you surely have something to protect. Security is something that concerns everybody, and this is your chance to test your creativity skills, or, better say, your knowledge of encryption algorithms. Join us at StudentHack and work on the Security track, to make sure nobody can easily hack into your accounts and be StudentHack's Security Challenge Winner."
          icon = "icon-lock"

        [[params.tracks.item]]
          title = "Big Data"
          description = "Data is all around us in many shapes and form, the challenge of aggregating the data to make decisions to improve businesses is what this track challenge is all about. Accenture faces this challenge daily and as such they adopting this track and offering complete mentorship support throughout the weekend. Join this track to mine all that data and create the next Skynet and be StudentHack’s BigData Challenge Winner."
          icon = "icon-chart"

        [[params.tracks.item]]
          title = "Education"
          description = "As a world without education is lost forever, if you have the will to improve something, join the Education track to come up with ideas that could change the system you're already a part of. Join this track share with us the next innovative idea for students and teachers and win StudentHack's Education Challenge."
          icon = "icon-graduation"

        [[params.tracks.item]]
          title = "Hardware & Automotive"
          description = "\"The hardware makes a machine fast, while the software makes a fast machine slow\" if you think that software is just a tool for hardware, then you would be happy to find we have a Hardware track to work on. Join this track and create the device everybody will be talking about in few years, by joining this track and be StudentHack's Hardware Challenge Winner."
          icon = "icon-settings"

        [[params.tracks.item]]
          title = "General"
          description = "Do you already have a great idea and you can't wait to work on it? You'll have the environment, the time, the resources and you'll be surrounded by the right people to do so. Join the Open track at StudentHack and you may be one of the StudentHack's Winners. "
          icon = "icon-globe"


  # Sponsors section
  [params.sponsors]
    enable = true
    enVenu = true
    enPlat = true
    enHard = true
    enTrac = true
    enGold = true
    enSilv = true
    enBron = true
    enPart = true
    title = "Sponsors"
    description = "They made it possible!"

    [[params.sponsors.venue]]
      img = "landing.png"
      alt = "The Landing"
      link = "http://www.thelanding.org.uk/"

    [[params.sponsors.platinum]]
      img = "riot.png"
      alt = "Riot"
      link = "https://riot.im"

    [[params.sponsors.platinum]]
      img = "matrix.png"
      alt = "Matrix"
      link = "https://matrix.org"

    [[params.sponsors.track]]
      img = "accenture.png"
      alt = "Accenture"
      link = "https://www.accenture.com"

    [[params.sponsors.track]]
      img = "webapps.png"
      alt = "WebApplicationsUk"
      link = "https://www.webapplicationsuk.com"

    [[params.sponsors.track]]
      img = "barclays.png"
      alt = "Barclays"
      link = "https://www.home.barclays/"

    [[params.sponsors.gold]]
      img = "cakesol.png"
      alt = "Cake Solutions"
      link = "http://www.cakesolutions.net"

    [[params.sponsors.silver]]
      img = "twilio.png"
      alt = "Twilio"
      link = "https://www.twilio.com/"

    [[params.sponsors.bronze]]
      img = "codethink.png"
      alt = "Codethink"
      link = "https://www.codethink.co.uk/"
    
    [[params.sponsors.bronze]]
      img = "floss.png"
      alt = "Floss" 
      link = "https://www.flossuk.org/"

    [[params.sponsors.bronze]]
      img = "telcom.png"
      alt = "Telcom"
      link = "https://telcom.io"
      
    [[params.sponsors.bronze]]
      img = "noma.png"
      alt = "Noma"
      link = "https://www.noma-manchester.com"

    [[params.sponsors.bronze]]
      img = "space48.png"
      alt = "Space 48"
      link = "https://www.space48.com"

    [[params.sponsors.bronze]]
      img = "morgans.png"
      alt = "Morgan Stanley"
      link = "https://www.morganstanley.com/"

    [[params.sponsors.hardware]]
      img = "google.png"
      alt = "Google"
      link = "https://get.google.com/tango/"
      
    [[params.sponsors.hardware]]
      img = "thalmic.png"
      alt = "ThalmicLabs"
      link = "https://www.thalmic.com/"

    [[params.sponsors.hardware]]
      img = "pebble.png"
      alt = "Pebble"
      link = "https://www.pebble.com/"

    [[params.sponsors.hardware]]
      img = "leap.png"
      alt = "LeapMotion"
      link = "https://www.leapmotion.com/"

    [[params.sponsors.hardware]]
      img = "oculus.png"
      alt = "OculusVr"
      link = "https://www.oculus.com"

    [[params.sponsors.hardware]]
      img = "muse.png"
      alt = "Muse"
      link = "http://www.choosemuse.com/"

    [[params.sponsors.hardware]]
      img = ""
      alt = ""
      link = ""

    [[params.sponsors.hardware]]
      img = "estimote.png"
      alt = "Estimote"
      link = "https://estimote.com/"

    [[params.sponsors.partner]]
      img = "monzo.png"
      alt = "Monzo"
      link = "https://monzo.com/"

    [[params.sponsors.partner]]
      img = "namebox.png"
      alt = "Namebox"
      link = "https://www.namebox.ro/"

  # Chart section
  [params.chart]
    enable = true
    title = "Registered"

  # Location section
  [params.location]
    enable = true
    map = true
    title = "Location"
    description = "The Landing, Blue, MediaCityUK, M50 2ST, Manchester, UK"

    [[params.location.option]]
	titl = "Option 1"
	desc = ["From Manchester Airport, take the tram towards Deansgate/Castlefield until the Cornbrook station",
		"Then change for the MediaCityUK tram and go until the last station. (total cost: £6.20)"]
    [[params.location.option]]
	titl = "Option 2"
	desc = ["From Manchester Airport take the train to Manchester Piccadilly (£5)",
		"From Manchester Piccadilly station, go downstairs to the tram station and take the tram to MediaCityUK. (£2.8 single / £3.90 return)"]
    [[params.location.option]]
	titl = "Useful links and information"
	desc = ["A volunteer will be in the MediaCityUK tram station, providing directions to the venue (aprox 3 min walk)",
   		'<a href="http://www.manchesterairport.co.uk/to-and-from-the-airport/metrolink/">To and from the airport - Metrolink</a>',
    		'<a href="http://www.metrolink.co.uk/stationinfo/Documents/Route_Map.pdf">Metrolink - Route map</a>',
    		'You can buy your ticket in advance or check ticket prices on <a href="http://www.metrolink.co.uk/tickets/Pages/ticketselector.aspx">Metrolink</a>']

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-power"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # Challenges section
  [params.challenges]
    title = "Challenges"

  # Contact section
  [params.contact]
    enable = false
    title = "Get in touch"
    description = "For any question, feedback or sponsorship proposal, feel free to contact us!"

    # Available icons: http://simplelineicons.com/

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a> <br> Adapted By  <a href="http://hacksoc.com/" target="_blank">HackSoc</a> Dev Team'
