# Page settings
baseurl = "localhost:1313"
title = "StudentHack V"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params] 
  custom_css = ["css/custom1.css"]

  # Meta
  author = "StudentHack V"
  description = "StudentHack V 2017 - #learn #build #share 10-12 March 2017"
  email = "hristeaanais@gmail.com"
  # Navigation
  [params.navigation]
    brand = "StudentHack V"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    sponsors = "Sponsors"
    chart = "Attendance"
    location = "Location"
    contact = "Get In Touch"
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = " "
    #  name = " "
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "10-12 March 2017 <br> Manchester, England"
    subtitle = "The epic student hackathon in Manchester <br> & we're making it more accessible than ever."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Yes, 100%."
      icon = "icon-wallet"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "All enrolled students over 18 and those who graduated in the last one year."
      icon = "icon-graduation"

    [[params.faq.item]]
      title = "What if I study outside the UK?"
      description = "You are still welcome to join us! However, we cannot sponsor visas."
      icon = "icon-plane"

    [[params.faq.item]]
      title = "I haven't coded much. Should I come?"
      description = "Hackathons are for beginners. Networking with and seeing awesome hackers in action will expose you to a tremendous amount of knowledge. There is an amazing suit of industry experts and mentors that are happy to assist you!"      
      icon = "icon-briefcase"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone and chargers. Other things to consider: spare clothes, adapters, hardware and a sleeping bag, oh and don't forget your enthusiasm! We are going to provide you with all the food, swag, sleeping rooms and the drinks that you will need."      
      icon = "icon-basket-loaded"

    [[params.faq.item]]
      title = "I don't have a team. Help?"
      description = "We encourage everybody to form a team with new people, regardless of whether you come with your buddies or not! We will organise a team-building session, where you will meet other participants just like you. Due to logistic restrictions, we ask for the teams to be of 4 people maximum."      
      icon = "icon-people"

    [[params.faq.item]]
      title = "What can I expect from StudentHack?"
      description = "An entire weekend of great company, good food and plenty of swag! We'll also have hardware and tons of mentors."      
      icon = "icon-magic-wand"

    [[params.faq.item]]
      title = "Who owns my IP/code/idea?"
      description = "You own all the rights to your intellectual property. We won't claim any right over anything made during this event."      
      icon = "icon-bulb"

    [[params.faq.item]]
      title = "Do you have a code of conduct?"
      description = "Yes! We strictly adhere to the <a href='https://static.mlh.io/docs/mlh-code-of-conduct.pdf'>Major League Hacking Code of Conduct</a>."      
      icon = "icon-book-open"

  # Schedule section
  [params.schedule]
    enable = true 
    title = "Schedule"

    [[params.schedule.friday]]
      time = "18:00"
      name = "Registration opens"

    [[params.schedule.friday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.friday]]
      time = "20:30"
      name = "Opening ceremony"

    [[params.schedule.friday]]
      time = "22:00"
      name = "Hacking starts<br>Team forming session"


    [[params.schedule.saturday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.saturday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.saturday]]
      time = "21:00"
      name = "MLH event"


    [[params.schedule.sunday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.sunday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.sunday]]
      time = "10:00"
      name = "Hacking ends"

    [[params.schedule.sunday]]
      time = "11:00"
      name = "Judging starts"

    [[params.schedule.sunday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.sunday]]
      time = "14:00"
      name = "Final presentations"

    [[params.schedule.sunday]]
      time = "16:00"
      name = "Closing ceremony"

    [[params.schedule.sunday]]
      time = "17:00"
      name = "End of the event"


  # Sponsors section
  [params.sponsors]
    enable = true
    enPlat = true
    enHard = true
    enTrac = true
    enGold = true
    enSilv = true
    enBron = true
    enPart = true
    title = "Sponsors"
    description = "They made it possible!"

    [[params.sponsors.platinum]]
      img = "riot.png"
      alt = "Riot"
      link = "https://riot.im"

    [[params.sponsors.platinum]]
      img = "matrix.png"
      alt = "Matrix"
      link = "https://matrix.org"

    [[params.sponsors.track]]
      img = "accenture.png"
      alt = "Accenture"
      link = "https://www.accenture.com"

    [[params.sponsors.track]]
      img = "webapps.png"
      alt = "WebApplicationsUk"
      link = "https://www.webapplicationsuk.com"

    [[params.sponsors.gold]]
      img = "cakesol.png"
      alt = "Cake Solutions"
      link = "http://www.cackesolutions.net"

    [[params.sponsors.silver]]
      img = "twilio.png"
      alt = "Twilio"
      link = "https://www.twilio.com/"

    [[params.sponsors.bronze]]
      img = "codethink.png"
      alt = "Codethink"
      link = "https://www.codethink.co.uk/"
    
    [[params.sponsors.bronze]]
      img = "noma.png"
      alt = "Noma"
      link = "https://www.noma-manchester.com"

    [[params.sponsors.bronze]]
      img = "telcom.png"
      alt = "Telcom"
      link = "https://telcom.io"

    [[params.sponsors.bronze]]
      img = ""
      alt = ""
      link = ""

    [[params.sponsors.bronze]]
      img = "morgans.png"
      alt = "Morgan Stanley"
      link = "https://www.morganstanley.com/"

    [[params.sponsors.hardware]]
      img = "google.png"
      alt = "Google"
      link = "https://get.google.com/tango/"

    [[params.sponsors.partner]]
      img = "monzo.png"
      alt = "Monzo"
      link = "https://monzo.com/"

    [[params.sponsors.partner]]
      img = "namebox.png"
      alt = "Namebox"
      link = "https://www.namebox.ro/"

  # Chart section
  [params.chart]
    enable = true
    title = "Registered"

  # Location section
  [params.location]
    enable = true
    map = true
    title = "Location"
    description = "The Landing, Blue, MediaCityUK, M50 2ST, Manchester, UK" 

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-power"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    title = "Get in touch"
    description = "For any question, feedback or sponsorship proposal, feel free to contact us!"
    
    # Available icons: http://simplelineicons.com/

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a> <br> Edited By  <a href="http://hacksoc.com/" target="_blank">HackSoc</a> Dev Team'
